#!/bin/bash

cd ..
# cleanup old build
rm -r dist
# use virtual environment
source src/venv/bin/activate
# get pyinstaller
pip install pyinstaller
# create spec file
pyinstaller --clean -ywF -i design/icon.ico -n chikkai src/main.py
# build exe
pyinstaller -y chikkai.spec
# unix setup
mv dist/chikkai dist/chikkai_e
mkdir dist/chikkai
mv dist/chikkai_e dist/chikkai/chikkai
# copy in assets
cp -r src/assets dist/chikkai/assets
# copy in readme
cp design/README.txt dist/chikkai/
# copy in license
cp LICENSE.txt dist/chikkai/
# unix final
chmod +x dist/chikkai
# cleanup
deactivate
rm -r build
rm chikkai.spec
