#!/bin/bash

cd ..
# cleanup old build
rm -r dist
# use virtual environment
source src/venv/bin/activate
# get pyinstaller
pip install pyinstaller
# create spec file
pyinstaller --clean -ywF -i design/icon.ico -n chikkai src/main.py
# build exe
pyinstaller -y chikkai.spec
# copy in assets
cp -r src/assets dist/chikkai/assets
# executable setup
chmod +x dist/chikkai
# cleanup
deactivate
rm -r build
rm chikkai.spec
