SCREEN_CAPTION = "Monsters and Stuff"
SCREEN_SIZE = (320, 180)
MAX_FRAMERATE = 60
CURSOR_TIME = 20
FONT_SIZE = 8
TEXT_COLOR = (164, 162, 165)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

GRAPHICS_DIRECTORY = 'gfx'
BACKGROUNDS_DIRECTORY = 'backgrounds'
MONSTER_PARTS_DIRECTORY = 'monster-parts'
FONT_FILE = 'simple_mono.ttf'

SAVE_DIRECTORY = 'savegames'
