name: build-dist
on:
  push:
    branches:
      master
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo ${{ env.name }}
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Setup pyinstaller
        run: pip install pyinstaller
      - name: Run build
        run: |
          pyinstaller --clean -ywF --name chikkai src/main.py
          pyinstaller -y chikkai.spec
          cp -r src/assets dist/assets
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: chikkai-build ${{ env.name }}
          path: dist/
          if-no-files-found: error
